# Numpy

In [1]:
import numpy as np

In [6]:
python_list = [100, 200, 300, 400, 500]
numpy_array = np.array(python_list)
print(type(numpy_array))
print(numpy_array)

<class 'numpy.ndarray'>
[100 200 300 400 500]


In [10]:
matrix1 = np.array([[1,1,1]
                   ,[2,2,2]
                   ,[3,3,3]])
print(matrix1)
type(matrix1)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


numpy.ndarray

In [19]:
array = np.arange(start =0, stop = 11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
array = np.arange(0,11)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
array = np.arange(0,200, 25)
print(array)
type(array)

[  0  25  50  75 100 125 150 175]


numpy.ndarray

In [24]:
matrix2 = np.linspace(0,100,10)
print(matrix2)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [25]:
matrix3 = np.zeros([3,5])
matrix3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
matrix4 = np.ones([3,5])
matrix4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
matrix5 = np.eye(6) # identity matrix
matrix5

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [28]:
array = np.arange(0,20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
array_reshaped = array.reshape((4,5))
array_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
list1 = [1,2,3,]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [32]:
array1 = np.array(list1)
array2 = np.array(list2)
array1 + array2

array([5, 7, 9])

# Pandas

In [34]:
import pandas as pd

In [35]:
day = ['day1', 'day2', 'day3', 'day4']
temperature = [31, 28, 30, 32] # temperature in degrees Celsius
temp_data = pd.Series(temperature, index=day)

In [36]:
temp_data[:2]

day1    31
day2    28
dtype: int64

In [37]:
temp_data['day3']

30

In [41]:
temp_data[2:]

day3    30
day4    32
dtype: int64

In [44]:
calorie_data = pd.DataFrame({'day': ['day1', 'day2', 'day3', 'day4', 'day5']
                                     ,'calories': [450, 300, 345, 520, 600]
                                     ,'duration_min': [30, 25, 29, 39, 48]
                                     })
calorie_data

day  calories  duration_min
0  day1       450            30
1  day2       300            25
2  day3       345            29
3  day4       520            39
4  day5       600            48

In [46]:
calorie_data[:2]

day  calories  duration_min
0  day1       450            30
1  day2       300            25

In [47]:
calorie_data['calories']

0    450
1    300
2    345
3    520
4    600
Name: calories, dtype: int64

In [48]:
calorie_data[::2]

day  calories  duration_min
0  day1       450            30
2  day3       345            29
4  day5       600            48

## Pandas (.loc)

In [49]:
calorie_data.loc[1]

day             day2
calories         300
duration_min      25
Name: 1, dtype: object

In [51]:
calorie_data.loc[[1],['calories']]

calories
1       300

In [53]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29


## Week 2: Practice Quiz Pandas

In [54]:
path = 'C:/Users/BoboDS/Desktop/Great_Learning/Great Learning/Week 2-Numpy and Pandas/books.csv'
books_df = pd.read_csv(path)

In [55]:
books_df.head()

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13 language_code  \
0                  Victor Hugo            4.00  9780345472427         en-US   
1  Lidia Matticchio Bastianich            4.14  9780767914222         en-GB   
2             James Scott Bell            4.00  9780310243878           eng   
3         David Foster Wallace            3.86  9780349111889           eng   
4          Laurell K. Hamilton            4.13  9780425209066         en-US   

   num_pages  ratings_count  text_reviews_count          publisher  year  
0      534.0            140                  22     Modern Library  2004  
1      288.0             48                   3    Clarkson Potter  2003  
2      345.0            368                  36          Zondervan  2004  
3      273.0          18335                1155             Abacus  2000  
4      368.0          59524                 946  Berkley Hardcover  2006

In [57]:
books_df.shape

(5000, 10)

In [58]:
books_df.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [59]:
books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [63]:
book_rating_greater_than_4 = books_df.loc[books_df['average_rating']>4]
book_rating_greater_than_4.shape

(2115, 10)

In [68]:
books_df[(books_df['average_rating']>4.5) & (books_df['ratings_count']<10)]

title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates: Computer Legend (Famous Lives)   
3706  A Wife After God's Own Heart Growth and Study ...   
3833  His Princess Devotional: A Royal Encounter Wit...   
3909                 Little Big Book for God's Children   
3927  Colossians and Philemon: A Critical and Exeget...   
4108                  Willem de Kooning: Late Paintings   
4415                                           Corvette   
4455  The Complete Theory Fun Factory: Music Theory ...   
4917                          Taxation of Mineral Rents   
4933  Oliver Wendell Holmes in Paris: Medicine  Theo...   

                             author  average_rating         isbn13  \
63                   Hiromu Arakawa            4.57  9789861156521   
178                  Hiromu Arakawa            4.58  9789861146140   
224                 Mary B. Collins            4.86  9781583372920   
454                  Tara MacCarthy            5.00  9780439271714   
584               Melissa M. Garcia            4.67  9780595377107   
681                  Chris    Green            5.00  9780310249870   
696                  Laura Driscoll            5.00  9780786845033   
741                   Don Macmillan            4.75  9780760329634   
757               James E. Campbell            5.00  9780890969403   
1837                     NOT A BOOK            5.00  9780563388692   
1856                 Hiromu Arakawa            4.60  9789861156538   
1960  Georg Wilhelm Friedrich Hegel            4.78  9783787307678   
2244                  Beth A. Jones            4.67  9781577948261   
2496             Frances J. Roberts            4.58  9781593109158   
3178                David A. Nadler            4.62  9781555424435   
3438               Sara Barton-Wood            5.00  9780739844328   
3706               Elizabeth George            4.69  9780736911689   
3833            Sheri Rose Shepherd            5.00  9781590529621   
3909                     Alice Wong            4.88  9780941807555   
3927                 R. McL. Wilson            5.00  9780567044716   
4108                Julie Sylvester            5.00  9783829602266   
4415                   Jerry Burton            4.83  9780883631218   
4455              Ian        Martin            5.00  9780851621814   
4917                   Ross Garnaut            5.00  9780198284543   
4933             William C. Dowling            5.00  9781584655800   

     language_code  num_pages  ratings_count  text_reviews_count  \
63             NaN      184.0              4                   0   
178            NaN      191.0              5                   0   
224            eng      210.0              5                   0   
454            eng       32.0              4                   1   
584            eng      216.0              1                   0   
681            eng      336.0              1                   1   
696            eng       24.0              2                   1   
741            eng      256.0              4                   0   
757            eng      314.0              0                   0   
1837          

In [76]:
books_df.groupby(['language_code']).mean()

C:\Users\BoboDS\AppData\Local\Temp\ipykernel_12744\3851432196.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  books_df.groupby(['language_code']).mean()


average_rating        isbn13   num_pages  ratings_count  \
language_code                                                            
en-GB                3.922523  9.696604e+12  341.339623    3341.766355   
en-US                3.914800  9.736889e+12  336.731366    4277.309231   
eng                  3.931143  9.754850e+12  341.497604   24326.628321   
ger                  3.979773  9.783368e+12  358.590909      88.477273   
grc                  2.366667  9.781553e+12  360.666667       2.333333   
jpn                  4.252381  9.784141e+12  191.857143      74.095238   
lat                  4.170000  9.780865e+12   75.000000      63.000000   
mul                  4.116000  9.780973e+12  447.000000     572.900000   
spa                  3.927938  9.785959e+12  345.875000    3465.927835   

               text_reviews_count         year  
language_code                                   
en-GB                  143.869159  2000.850467  
en-US                  178.353846  2000.824615  
eng                    705.539348  1999.994236  
ger                      4.863636  1998.454545  
grc                      0.333333  1987.333333  
jpn                      4.428571  2001.000000  
lat                      9.000000  2005.000000  
mul                     31.000000  1982.400000  
spa                     95.463918  2003.185567

In [77]:
books_df.iloc[0:5,0:4]

title  \
0                        The Hunchback of Notre-Dame   
1  La Cucina Di Lidia: Recipes and Memories from ...   
2                                  Breach of Promise   
3                  Brief Interviews with Hideous Men   
4  The Killing Dance (Anita Blake  Vampire Hunter...   

                        author  average_rating         isbn13  
0                  Victor Hugo            4.00  9780345472427  
1  Lidia Matticchio Bastianich            4.14  9780767914222  
2             James Scott Bell            4.00  9780310243878  
3         David Foster Wallace            3.86  9780349111889  
4          Laurell K. Hamilton            4.13  9780425209066

In [80]:
books_df.loc[[1,4],['language_code','num_pages','ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
4         en-US      368.0          59524

In [81]:
books_df['num_pages'].mean()

341.0940205355345

In [82]:
books_df['num_pages'].mode()

0    288.0
Name: num_pages, dtype: float64

In [83]:
books_df['num_pages'].median()

304.0

In [84]:
books_df['num_pages'].max()

3342.0

In [106]:
books_by_year = books_df.groupby(['year'])
print(books_by_year)

In [121]:
books_df.iloc[:,9].value_counts()

2006    720
2005    531
2004    493
2003    423
2002    338
       ... 
1961      1
1952      1
1931      1
1966      1
1921      1
Name: year, Length: 74, dtype: int64

In [128]:
books_df.loc[books_df['year']==2010].shape

(15, 10)

In [159]:
books_df[(books_df['publisher'] == 'DAW') & (books_df['average_rating'] > 4)]

title           author  \
71                           By the Sword (Valdemar)  Mercedes Lackey   
871         Storm Rising (Valdemar: Mage Storms  #2)  Mercedes Lackey   
1523       Phoenix and Ashes (Elemental Masters  #3)  Mercedes Lackey   
1583  To Battle the Gods (Jalav  Amazon Warrior  #5)     Sharon Green   
3726        Oathblood (Valdemar: Vows and Honor  #3)  Mercedes Lackey   
4367                     Joust (Dragon Jousters  #1)  Mercedes Lackey   

      average_rating         isbn13 language_code  num_pages  ratings_count  \
71              4.25  9780886774639           eng      492.0          18531   
871             4.02  9780886777128         en-US      412.0          10781   
1523            4.01  9780756402723           eng      480.0           6980   
1583            4.07  9780886771287           eng      446.0             87   
3726            4.06  9780886777739         en-GB      394.0           9786   
4367            4.02  9780756401535           eng      448.0          10113   

      text_reviews_count publisher  year  
71                   249       DAW  1991  
871                   86       DAW  1996  
1523                 229       DAW  2005  
1583                   1       DAW  1986  
3726                 103       DAW  1998  
4367                 263       DAW  2004

In [160]:
books_df[(books_df['num_pages'] > 500) & (books_df['year'] > 2010)]

title               author  \
2045  Billy Budd  Sailor and Other Uncompleted Writi...      Herman Melville   
2775          Rick Steves' Europe Through the Back Door          Rick Steves   
3075                                          The Iliad                Homer   
3157                    George Washington's Sacred Fire    Peter A. Lillback   
3546                                  The Will to Power  Friedrich Nietzsche   

      average_rating         isbn13 language_code  num_pages  ratings_count  \
2045            3.11  9780810111141           eng     1016.0              0   
2775            4.24  9781566918084           eng      808.0           3569   
3075            3.86  9781904633389           eng      542.0             64   
3157            4.18  9780978605261           eng     1200.0            694   
3546            4.05  9780394704371           eng      575.0           7931   

      text_reviews_count                publisher  year  
2045                   0  Northwestern Univ Press  2017  
2775                  70            Avalon Travel  2017  
3075                   8      Collector's Library  2011  
3157                  63   Providence Forum Press  2011  
3546                 132            Vintage Books  2011

In [161]:
books_df[(books_df['author'] == 'Agatha Christie')].count()

title                 21
author                21
average_rating        21
isbn13                21
language_code         21
num_pages             19
ratings_count         21
text_reviews_count    21
publisher             21
year                  21
dtype: int64

In [162]:
books_df[(books_df['language_code'] == 'spa') & (books_df['year'] > 2000)]

title  \
21                      Los funerales de la Mamá Grande   
53    La Emperatriz tras el velo (Trilogía Taj Mahal...   
69                             La casa de los espíritus   
93                                  Ya Sé Que Te Quiero   
107                                 Secretos De Familia   
...                                                 ...   
4804                                      Muerte Blanca   
4832  Entrevista con el vampiro (Crónicas vampíricas...   
4890         Isabel: Princesa De Castilla  España  1466   
4907                                     Ve  perro ¡Ve!   
4951                                El librero de Kabul   

                      author  average_rating         isbn13 language_code  \
21    Gabriel García Márquez            3.78  9780307350329           spa   
53           Indu Sundaresan            4.04  9788425337604           spa   
69            Isabel Allende            4.23  9780060951306           spa   
93             Billy Crystal            4.19  9780060845988           spa   
107              Julia Glass            3.57  9788496525030           spa   
...                      ...             ...            ...           ...   
4804           Clive Cussler            3.91  9780307343260           spa   
4832               Anne Rice            3.99  9788466616201           spa   
4890           Carolyn Meyer            3.71  9788478886746           spa   
4907            P.D. Eastman            4.09  9780375823619           spa   
4951          Åsne Seierstad            3.76  9789706519245           spa   

      num_pages  ratings_count  text_reviews_count                publisher  \
21        160.0           4694                 133            Plaza y Janes   
53        382.0              2                   1    Grijalbo Mondadori Sa   
69        454.0            608                  38    HarperCollins Espanol   
93         40.0              0                   0                     Rayo   
107       528.0              0                   1              Puzzle-Roca   
...         ...            ...                 ...                      ...   
4804      421.0              2                   0               Debolsillo   
4832      463.0           1307                  93              Ediciones B   
4890      184.0              8                   0               Salamandra   
4907       24.0             33                   2  Random House Para Ninos   
4951      285.0            112                  18             Grupo Océano   

      year  
21    2006  
53    2003  
69    2001  
93    2006  
107   2006  
...    ...  
4804  2005  
4832  2005  
4890  2001  
4907  2003  
4951  2004  

[84 rows x 10 columns]

## Week 2: Graded Quiz

In [165]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
demo_matrix

demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [178]:
demo_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
demo_array[0:7] = 5
demo_array

array([5, 5, 5, 5, 5, 5, 5, 7, 8, 9])

In [182]:
demo_array = np.arange(0,10)
demo_array
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [183]:
flowers = pd.Series([2, 3, 5, 4], index = ['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [236]:
data_customer = pd.DataFrame({'customer': [101, 102, 103, 104 ,101, 103]
                              ,'category': ['cat2', 'cat2', 'cat1', 'cat3', 'cat2', 'cat1']
                              ,'important': ['yes', 'no', 'yes', 'yes', 'yes', 'yes']
                              ,'sales': [123, 52, 214, 663, 204, 453]})
data_customer

customer category important  sales
0       101     cat2       yes    123
1       102     cat2        no     52
2       103     cat1       yes    214
3       104     cat3       yes    663
4       101     cat2       yes    204
5       103     cat1       yes    453

In [192]:
# data_customer(['category'])['customer'].value_counts()
data_customer['category'].value_counts()

cat2    2
cat1    1
cat3    1
Name: category, dtype: int64

In [194]:
data_customer(['category'])['customer'].value_counts()

TypeError: 'DataFrame' object is not callable

In [198]:
data_customer.sort_values(by = 'sales', ascending = False)

customer category important  sales
3       104     cat3       yes    663
2       103     cat1       yes    214
0       101     cat2       yes    123
1       102     cat2        no     52

In [205]:
data_customer.iloc[[1:3],[0,4]]

SyntaxError: invalid syntax (2777647647.py, line 1)

In [221]:

# store_data.loc[[1,4],['location','type']]

customer  sales
1       102     52
2       103    214
3       104    663

In [219]:
data_customer.loc[[1,2],[0,3]]# This doesn't work because loc only uses labels

KeyError: "None of [Int64Index([0, 3], dtype='int64')] are in the [columns]"

In [216]:
data_customer.loc[[1:3], ['customer', 'sales']]

SyntaxError: invalid syntax (316477982.py, line 1)

In [218]:
data_customer.loc[1:3, ['customer', 'sales']]

customer  sales
1       102     52
2       103    214
3       104    663

In [235]:
data_customer.loc[[1,2], ['customer', 'sales']]
# data_customer.loc[[1,3],['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [239]:
data_customer.groupby(['customer'])['sales'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64